# Generated by Django 2.0.5 on 2018-06-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createid',
            name='encoded_image',
            field=models.CharField(default=0, max_length=245000),
            preserve_default=False,
        ),
    ]
