# Generated by Django 2.0.5 on 2018-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_createid_encoded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createid',
            name='client_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='createid',
            name='restaurant_id',
            field=models.UUIDField(),
        ),
    ]
