# Generated by Django 2.1 on 2018-08-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180803_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_imgs',
            name='encoded_image',
        ),
        migrations.AddField(
            model_name='client_imgs',
            name='image_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
